# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  tags:
    include:
    - release/*

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
    mac:
      imageName: 'macos-10.13'
    windows:
      imageName: 'vs2017-win2016'
      
pool:
  vmImage: $(imageName)

steps:
- script: |
    git submodule update --init
  displayName: 'Update submodules'
- task: CMake@1
  inputs:
    cmakeArgs: '-DCMAKE_INSTALL_PREFIX=$(Build.BinariesDirectory) -DCMAKE_BUILD_TYPE=Release -S ..'
  displayName: 'Generate makefiles'
- task: CMake@1
  inputs:
    cmakeArgs: '--build . --config Release --target install'
  displayName: 'Build'
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)/b/bin' 
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Agent.OS).zip' 
    replaceExistingArchive: true 
  displayName: 'Archive files'
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: binaries
  displayName: 'Publish artifact'
